apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: ${NAMESPACE}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "trade/${NAMESPACE}/api-key"
        objectType: "secretsmanager"
  secretObjects:
  - secretName: app-secrets
    type: Opaque
    data:
    - objectName: "trade/${NAMESPACE}/api-key"
      key: API_KEY
